# Generated by Django 3.2 on 2021-04-24 19:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('task', models.TextField()),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2021, 4, 24, 19, 46, 55, 892487, tzinfo=utc), verbose_name='Time published')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
