# Generated by Django 3.2 on 2021-04-24 19:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 24, 19, 33, 39, 680864, tzinfo=utc), verbose_name='Time published'),
        ),
    ]
